[package]
name = "dionysos"
version = "0.1.3"
edition = "2018"
description = "Scanner for various IoCs"
homepage = "https://www.github.com/janstarke/dionysos"
license = "GPL-3.0"
authors = ["Jan Starke <Jan.Starke@t-systems.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3"
simplelog = "0.11"
log = "0.4"
walkdir = "2"
yara = "0.12"
zip = "0.5"
regex = "1.5"
dionysos-derives = "0.1"