[package]
name = "dionysos"
version = "0.4.2"
edition = "2018"
description = "Scanner for various IoCs"
homepage = "https://www.github.com/janstarke/dionysos"
license = "GPL-3.0"
authors = ["Jan Starke <Jan.Starke@t-systems.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = {version="3", features=["derive"]}
clap-verbosity-flag = {version="1.0.0"}
simplelog = "0.12"
log = "0.4"
walkdir = "2"
yara = "0.12"
zip = "0.5"
regex = "1.5"
indicatif = "0.16"
futures = {version="0.3", features=["executor", "thread-pool"]}
filemagic = "0"

flate2 = "1"
bzip2 = "0.4"
xz = "0.1"