[package]
name = "dionysos"
version = "0.1.0"
edition = "2021"
description = "Scanner for various IoCs"
homepage = "https://www.github.com/janstarke/regview"
license = "GPL-3.0"
authors = ["Jan Starke <Jan.Starke@t-systems.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3"
simplelog = "0.11"
log = "0.4"
walkdir = "2"
yara = "0.12"
zip = "0.5"
regex = "1.5"
dionysos-provider-derive = { path = "provider-derive", version="0.1" }
dionysos-consumer-derive = { path = "consumer-derive", version="0.1" }
